/** 
 * Katherine Tran
 * 
 * This program implements the Comparable interface to allow for sorting of buses by their ID numbers.
 */
public class Bus implements Comparable<Bus> {

   private static int nextID = 1;
  
   private int number;
   private int route;
   
   public Bus() {
      this.number = nextID++;
      this.route = 0;
   } 
  
   /**
   * Constructs a new Bus object with a unique number and default route of 0.
   * The unique number is generated by incrementing the static class variable nextID.
   */
   public int getNumber() { return this.number; }
   public int getRoute() { return this.route; }
   public void setRoute(int route) { this.route = route; }
   
   public String toString() {
      return "BUS #" + getNumber() + " traveling ROUTE #" + getRoute();
   }

   /**
    * Returns a string representation of the Bus object in the format "BUS #[number] traveling ROUTE #[route]".
    * @return a string representation of the Bus object
    */
   @Override
   public int compareTo(Bus other) {
      if (this.number < other.number) {
         return -1;
      } else if (this.number > other.number) {
         return 1;
      } else {
         return 0;
      }
   }
}
